# Generated by Django 2.2.6 on 2019-10-24 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=900)),
            ],
        ),
        migrations.CreateModel(
            name='External_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url_logo', models.URLField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=500)),
                ('person_photo_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Welcome_message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=900)),
            ],
        ),
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_url', models.URLField()),
                ('name', models.CharField(help_text='Introduzca el título del portal', max_length=100)),
                ('about', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.About')),
                ('external_links', models.ManyToManyField(to='portal.External_link')),
                ('reviews', models.ManyToManyField(to='portal.Review')),
                ('welcome_message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.Welcome_message')),
            ],
        ),
    ]
